
server:
 port: 1112
     
spring: 
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT&useSSL=false
    username: root 
    password: root
  thymeleaf: 
    cache: false
    encoding: utf-8
    mode: HTML5
    suffix: .html
    prefix: classpath:/templates/
mybatis:
  mapper-locations: classpath:mapper/*.xml

